//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] AgzrtCryptProvider_Setup {
            get {
                object obj = ResourceManager.GetObject("AgzrtCryptProvider_Setup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] cadesplugin {
            get {
                object obj = ResourceManager.GetObject("cadesplugin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] capicom {
            get {
                object obj = ResourceManager.GetObject("capicom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ;
        ///;DestDir can be 10 for Windows directory, 11 for Windows\System(32) directory.
        ///
        ///[version]
        ///; version signature (same for both NT and Win95) do not remove
        ///signature=&quot;$CHICAGO$&quot;
        ///AdvancedINF=2.0
        ///
        ///[SourceDisksNames]
        ///; This section specifies that all sources are in the &quot;default&quot; location.
        ///1=&quot;default&quot;,,1
        ///
        ///[DefaultInstall]
        ///; Default section to process and copy all files under the section
        ///; capicom.files and Register DLLs under the section capicom.register.
        ///CopyFiles=capicom.files
        ///RegisterOCXs=capi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string capicom1 {
            get {
                return ResourceManager.GetString("capicom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] casert {
            get {
                object obj = ResourceManager.GetObject("casert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CSPSetup {
            get {
                object obj = ResourceManager.GetObject("CSPSetup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\OID\EncodingType 0\CryptDllFindOIDInfo]
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\OID\EncodingType 0\CryptDllFindOIDInfo\1.2.643.6.3.1!1]
        ///&quot;Name&quot;=&quot;Использование на электронных площадках, отобранных для проведения аукционов в электронной форме&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\OID\EncodingType 0\CryptDllFindOIDInfo\1.2.643.6.3.4!2]
        ///&quot;Name&quot;=&quot;Полномочия - Уполномоченный специалист&quot;
        ///
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string express_oids {
            get {
                return ResourceManager.GetString("express_oids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ICLCrypt {
            get {
                object obj = ResourceManager.GetObject("ICLCrypt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon logo_ee {
            get {
                object obj = ResourceManager.GetObject("logo_ee", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon logo_wh {
            get {
                object obj = ResourceManager.GetObject("logo_wh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] rootsert {
            get {
                object obj = ResourceManager.GetObject("rootsert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] rtDrivers {
            get {
                object obj = ResourceManager.GetObject("rtDrivers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] XMLDSigAddIn_x64 {
            get {
                object obj = ResourceManager.GetObject("XMLDSigAddIn_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
